#!/usr/bin/env fish

set script_path (realpath (status -f))
set script_dir (dirname $script_path)

set machine_type (uname -m)

if test $machine_type = "arm64"
    set HOMEBREW_BASE_DIR /opt/homebrew
else
    set HOMEBREW_BASE_DIR /usr/local
end

set HOMEBREW_BIN_DIR $HOMEBREW_BASE_DIR/bin

set WORKSPACE_DIR $HOME/workspace

set -x PATH $PATH $HOMEBREW_BIN_DIR

for file in $script_dir/PATH_*
    source $file
end
